name: Workflow for Python using Snyk 
on: 
  pull_request:
    branches:
      - master
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      id: snyk_step_id
    
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --summary
        # If you want to monitor a project after workflow runs:
        # command: monitor
    
      
    - name: Create and issue
      if: failure()
      uses: maxkomarychev/oction-create-issue@v0.7.1
      env:
        gh_actor: $GITHUB_ACTOR
        gh_repo: $GITHUB_REPOSITORY
        gh_event_name: $GITHUB_EVENT_NAME
      with:
        token: ${{ secrets.GITHUB }}
        title: New issue created by $gh_actor
        body: There is a new issue in $gh_repo created by $gh_actor via a $gh_event_name
